let current=null, data=null, lastOutput=''; const $=s=>document.querySelector(s); const toast=t=>{const e=$('#toast');e.textContent=t;e.style.display='block';setTimeout(()=>e.style.display='none',2200)};
async function api(url,opt={}){if(opt.body){opt.headers={'Content-Type':'application/json'};opt.body=JSON.stringify(opt.body)}const r=await fetch(url,opt),j=await r.json();if(!r.ok)throw Error(j.error||'Request failed');return j}
async function catalog(){const rows=await api('/api/items');$('#items').innerHTML=rows.map(x=>`<button class="item" data-id="${x.id}"><span>${esc(x.title||'Untitled')}<small>${x.id} · ${x.status}</small></span><b>$${(+x.price).toFixed(2)}</b></button>`).join('')||'<p>No listings yet.</p>';document.querySelectorAll('.item').forEach(b=>b.onclick=()=>openItem(b.dataset.id))}
function esc(s=''){return s.replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
async function openItem(id){current=id;data=await api('/api/items/'+id);['title','description','condition_text','category','price','quantity','shipping'].forEach(k=>$('#'+k).value=data[k]??'');renderPhoto();renderBids();$('#capture').hidden=true;$('#editor').hidden=false}
function renderPhoto(){const p=data.photos?.[0];$('#photo').style.backgroundImage=p?`url(/photos/${p.path.split('/').pop()})`:'';$('#photo').classList.toggle('has',!!p)}
function renderBids(){const a=data.auction;$('#bidBox').hidden=!a;if(!a)return;$('#bids').innerHTML=(a.bids||[]).map((b,i)=>`<div class="bid"><span>${i===0?'🏆 ':''}${esc(b.bidder)}</span><b>$${(+b.amount).toFixed(2)}</b></div>`).join('')}
async function save(){const body={};['title','description','condition_text','category','price','quantity','shipping'].forEach(k=>body[k]=$('#'+k).value);body.price=+body.price;body.quantity=+body.quantity;data=await api('/api/items/'+current,{method:'PUT',body});toast('Saved')}
$('#newBtn').onclick=async()=>{const x=await api('/api/items',{method:'POST',body:{title:'New item',price:3}});openItem(x.id)};$('#back').onclick=()=>{$('#editor').hidden=true;$('#capture').hidden=false;catalog()};$('#save').onclick=save;
$('#camera').onclick=async()=>{try{toast('Opening camera…');data=await api(`/api/items/${current}/camera`,{method:'POST',body:{}});renderPhoto();toast('Photo saved')}catch(e){toast(e.message)}};
$('#analyze').onclick=async()=>{try{toast('Analyzing…');const x=await api(`/api/items/${current}/analyze`,{method:'POST',body:{}});for(const k of ['title','description','condition_text','category'])if(x[k])$('#'+k).value=x[k];if(x.suggested_price)$('#price').value=x.suggested_price;toast('Review the AI draft')}catch(e){toast(e.message)}};
document.querySelectorAll('nav button').forEach(b=>b.onclick=async()=>{await save();const ch=b.dataset.channel;const x=await api(`/api/export/${current}/${ch}`);lastOutput=ch==='facebook'?x.post:JSON.stringify(x,null,2);$('#output').textContent=lastOutput;$('#auction').hidden=ch!=='facebook';if(ch==='facebook')renderBids()});
$('#copy').onclick=async()=>{await navigator.clipboard.writeText(lastOutput||$('#output').textContent);toast('Copied')};
$('#createAuction').onclick=async()=>{data=await api(`/api/items/${current}/auction`,{method:'POST',body:{start_price:+$('#startPrice').value,increment:+$('#increment').value,ends_at:$('#ends').value}});renderBids();toast('Bid ledger started')};
$('#addBid').onclick=async()=>{try{data=await api(`/api/auctions/${data.auction.id}/bids`,{method:'POST',body:{bidder:$('#bidder').value,amount:+$('#amount').value}});renderBids();$('#bidder').value='';$('#amount').value=''}catch(e){toast(e.message)}};
$('#settingsBtn').onclick=async()=>{const s=await api('/api/settings');$('#ollama').value=s.ollama_url;$('#model').value=s.vision_model;$('#settings').showModal()};$('#saveSettings').onclick=()=>api('/api/settings',{method:'POST',body:{ollama_url:$('#ollama').value,vision_model:$('#model').value}});
catalog();
